<?php

namespace App\AdminModels;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'desc','slug','content','cat_id', 'icon', 'img'];

    //подготовка файлов перед сохранением
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model){
            $arr=[];
            foreach ($model->img as $image) {
                //сохранение файлов в папке на сервере /storage/app/images и присвоение им уникального имени
                $filename = \Storage::putFile('images',$image);
                //сохрание файлов в массиве
                $arr[] = $filename;
            }
            $images = implode(' ', $arr);
            $model->img = $images;
        });
    }

    public function category ()
    {
       return $this->belongsTo('App\AdminModels\Category','cat_id');
    }

    public function tags ()
    {
        return $this->belongsToMany('App\AdminModels\Tag', 'posts_tags', 'post_id', 'tag_id');
    }

}
